import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  ManyToOne,
  JoinColumn,
  Index,
} from 'typeorm';
import { User } from '../../user/entities/user.entity';

@Entity('expenses')
@Index('idx_expenses_user_date', ['userId', 'expenseDate'])
export class Expense {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'user_id' })
  userId: string;

  @ManyToOne(() => User)
  @JoinColumn({ name: 'user_id' })
  user: User;

  /** Full-resolution Cloudinary URL */
  @Column({ name: 'image_url' })
  imageUrl: string;

  /** 400×400 WebP thumbnail — generated by Cloudinary eager transform at upload time */
  @Column({ name: 'thumbnail_url', nullable: true, type: 'text' })
  thumbnailUrl: string | null;

  /** GPS latitude captured from EXIF or device location */
  @Column({ name: 'latitude', nullable: true, type: 'decimal', precision: 10, scale: 7 })
  latitude: number | null;

  /** GPS longitude captured from EXIF or device location */
  @Column({ name: 'longitude', nullable: true, type: 'decimal', precision: 11, scale: 7 })
  longitude: number | null;

  /** Reverse-geocoded label, e.g. "Quận 1, TP. Hồ Chí Minh" */
  @Column({ name: 'location_name', nullable: true, type: 'text' })
  locationName: string | null;

  @Column({ type: 'bigint', transformer: { to: (v: number) => v, from: (v: string) => parseInt(v, 10) } })
  amount: number;

  @Column({ nullable: true, type: 'text' })
  note: string | null;

  @Column({ name: 'expense_date', type: 'date' })
  expenseDate: string;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;
}
