import {
  IsString,
  IsNotEmpty,
  IsInt,
  Min,
  IsOptional,
  IsDateString,
  IsNumber,
  Max,
} from 'class-validator';
import { Type } from 'class-transformer';

export class CreateExpenseDto {
  @IsString()
  @IsNotEmpty()
  imageUrl: string;

  /** 400×400 WebP thumbnail generated by Cloudinary eager transform */
  @IsOptional()
  @IsString()
  thumbnailUrl?: string;

  @Type(() => Number)
  @IsInt()
  @Min(1, { message: 'amount must be greater than 0' })
  amount: number;

  @IsOptional()
  @IsString()
  note?: string;

  @IsDateString({}, { message: 'expenseDate must be a valid date (YYYY-MM-DD)' })
  expenseDate: string;

  @IsOptional()
  @IsNumber()
  @Min(-90)
  @Max(90)
  latitude?: number;

  @IsOptional()
  @IsNumber()
  @Min(-180)
  @Max(180)
  longitude?: number;

  /** Reverse-geocoded label, e.g. "Quận 1, TP. Hồ Chí Minh" */
  @IsOptional()
  @IsString()
  locationName?: string;
}
